### ISSUE TITLE
What is the intended structure for this project?

### ISSUE THREAD

**Issue by lukekrikorian** [JettBurns14/KACP-history#1]
Currently this is only an essentially blank README file. Are you planning on having the information stored in the Wiki? Miscellaneous markdown files?

**Comment by OOPS-Studio** [comment]
Yeah, I agree with Luke! :) (BTW, Howdy, Jett! ;)) I think it would be cool if you explained this a little bit! ;) Also, will it be a wiki, or will they be a bunch of .md files? :P (Also, do I count as an OG? ;3)

**Comment by lukekrikorian** [comment]
Perhaps instead of rehashing my already posted issue, it would be sufficient to post a reaction onto the original issue. The absurd amount of emoticons certainly don't help with readability either.

**Comment by OOPS-Studio** [comment]
Whoa, dude. Calm down! :P
1. Did what I did hurt anybody? No.
2. Yeah, in your opinion. But don't force it on me.
3. Well, I'm from Khan Academy, and Jett and I are kinda friends... XD (I mean, we talk about code! ;3) And he knows that I use a lot of emojis. I've been made fun of for it before, but I don't really care. I'll keep using them as long as it doesn't hurt anyone! ;) (Which it never has.)

**Comment by lukekrikorian** [comment]
I can understand and appreciate your friendliness, but GitHub issues aren't really the place to have off-topic discussion like this. Perhaps if you want to contact Jett you could use a different platform like Discord or e-mail. 

The only reason I requested that you instead post a reaction over a completely new comment is to reduce the amount of notifications Jett and I (and anyone with notifications on for this issue) has to deal with.

**Comment by OOPS-Studio** [comment]
1. Meh. Nobody cares! XD I mean, seriously, it doesn't matter! ;3 I mean, it's not like sending a "personal" message through GitHub matters to anyone... Do you know what I mean? Just because it's not "meant" for this, doesn't mean I can't use it for this... ?
2. Yes, I know, but my intent was for Jett to see the notif... You know? I was trying to get his attention... (Because I figured he missed your notif or something similar! ;))

**Comment by JettBurns14** [comment]
I didn't think about any details when I made this repo, just created a place where this project could happen. If something did come of this idea, it would probably be a simple website with a timeline where the history data is displayed in chronological order. I think it'd be really cool, but it'd take tons of time, effort, and research from several people to write even some of the history down. I couldn't do it myself.

Luke it right BTW, the 👍 ("+1") emoji is what you should have used, Oops, that's what it's there for. You can leave other comments, but repeating another comment isn't necessary. Not being mean, this is how things work in the professional coding world on GitHub.
